import { SignIn, useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage } from "~/components/loading";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
	const { user } = useUser();

	if (!user) return null;

	return (
		<div className="flex gap-3 w-full">
			<Image
				src={user.profileImageUrl}
				className="w-14 h-14 rounded-full"
				alt="Profile img"
				width={56}
				height={56}
			/>
			<input
				placeholder="What's on your mind? Emoji Edition"
				className="bg-transparent grow outline-none"
			/>
		</div>
	);
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
	const { post, author } = props;

	if (!author.username) return <div>No data available</div>;
	
	return (
		<div key={post.id} className="flex p-4 border-b border-slate-400 gap-4">
			<Image
				src={author.profileImageUrl}
				alt="Profile Image"
				className="w-14 h-14 rounded-full"
				width={56}
				height={56}
			/>
			<div className="flex flex-col">
				<div className="flex text-slate-300 gap-1">
					<span>{`@${author.username}`}</span>
					<span className="font-thin">{`· ${dayjs(
						post.createdAt,
					).fromNow()}`}</span>
				</div>
				<span className="text-2xl">{post.content}</span>
			</div>
		</div>
	);
};

const Feed = () => {
	const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

	if (postsLoading) return <LoadingPage />;

	if (!data) return <div>No data available</div>;

	return (
		<div className="flex flex-col">
			{[...data, ...data]?.map((fullPost) => (
				<PostView {...fullPost} key={fullPost.post.id} />
			))}
		</div>
	);
};

const Home: NextPage = () => {
	const { isLoaded: userLoaded, isSignedIn } = useUser();
	api.posts.getAll.useQuery();

	if (!userLoaded) return <div />;

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex h-screen justify-center">
				<div className="w-full md:max-w-2xl border-x border-slate-400">
					<div className="flex border-b border-slate-400 p-4">
						{!isSignedIn && (
							<div className="flex justify-center">
								<SignInButton />
							</div>
						)}
						{isSignedIn && <CreatePostWizard />}
					</div>
					<Feed />
				</div>
			</main>
		</>
	);
};

export default Home;
